version: "3"

services:
  database:
    image: postgres:alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - postgres-compose-network
  app:
    build: .
    command: npm start
    container_name: app
    ports:
      - "50052:50052"
    volumes:
      - .:/usr/app
    networks:
      - postgres-compose-network
    depends_on:
      - database
networks:
  postgres-compose-network:
    driver: bridge
